spring.application.name=recruitment-system
spring.datasource.url=jdbc:postgresql://localhost:5432/recruitment_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=20MB
server.port=6083


